apiVersion: v1
kind: Service
metadata:
  name: shopcart
spec:
  selector:
    app: shopcart
  type: NodePort
  internalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 31001
      targetPort: 8080
